version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: game_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - game
    ports:
    - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: game_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - game

  mysql:
    image: mysql:8.0
    container_name: game_mysql
    environment:
      MYSQL_DATABASE: game_database
      MYSQL_USER: game_user
      MYSQL_PASSWORD: game123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - game

  redis:
    image: redis:alpine
    container_name: game_redis
    networks:
      - game

networks:
  game:

volumes:
  mysql_data:
